receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:14317
      http:
        endpoint: localhost:14318

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: localhost:4317
    tls:
      insecure: true

processors:
  batch:

connectors:
  example:
    attribute_name: db.name

service:
  pipelines:
    traces:
      receivers: [example]
      exporters: [debug, otlp]
    logs:
      receivers: [otlp]
      exporters: [example]